# Generated by Django 5.2.4 on 2025-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
